### ISSUE TITLE
How to use sketch-threejs, Did you have any documents?

### ISSUE THREAD

**Issue by lidianhao123** [ykob/sketch-threejs#2]
Hello, I'm find sketch-three.js is very interesting. I want to try use it. Could you give me some detail documents or example？

**Comment by ykob** [comment]
there is no documents. but you can find source codes in this repository.
Please refer to the following directory.

https://github.com/ykob/sketch-threejs/tree/master/src/js
https://github.com/ykob/sketch-threejs/tree/master/src/glsl

JavaScript is converted by babel and browserify.

**Comment by caokaifeng** [comment]
I,ve never been used it before
 
 
------------------ Original ------------------

**Comment by ykob** [comment]
@caokaifeng 
You are included in the participants.
If you don't needs notifications, please turn off subscribe of this issue.
