### ISSUE TITLE
put site behind HTTPS

### ISSUE THREAD

**Issue by tetreault** [ykob/sketch-threejs#7]
otherwise webcam demos wont work

**Comment by ykob** [comment]
@tetreault HTTPS is enabled on GitHub Pages.
https://ykob.github.io/sketch-threejs/sketch/webcam.html

**Comment by tetreault** [comment]
Then just update the URL used in the repo since it points to HTTP :)

**Comment by ykob** [comment]
@tetreault Oh sorry for that. I updated URL of the repo.
